version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "beta"
    versioning-strategy: increase-if-necessary
    ignore:
      - dependency-name: "husky"
        versions: ["5.x"]
